name: Go CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build Standard
      run: go build -v ./...

    - name: Build with Legacy tags
      run: go build -v -tags "legacy legacy_avi legacy_asf legacy_rm legacy_mp2 legacy_codecs" ./...

    - name: Run standard tests
      run: go test -v -coverprofile=coverage.out ./...

    - name: Run tests with Legacy tags
      run: go test -v -tags "legacy legacy_avi legacy_asf legacy_rm legacy_mp2 legacy_codecs" ./...

    - name: Verify Coverage
      run: |
        cover_val=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
        echo "Total code coverage: $cover_val%"
